/* Automatically generated by './build/bin/build-ts.js' */
import { Button } from './button';
import { Confirm as MTDConfirm } from './confirm';
import {
  Message as MTDMessage,
  MessageOptions
} from './message';
import {
  Notification as MTDNotification,
  NotificationOptions
} from './notification';
import { FormRule, FormRules } from './form';
import CollapseTransition from './collapse-transition';

export const Message: MTDMessage;
export const Notification: MTDNotification;
export const Confirm: MTDConfirm;

export {
  Button,
  FormRule,
  FormRules,
  NotificationOptions,
  MessageOptions,
  CollapseTransition,
};

export declare function install(vue: any): void;

declare module 'vue/types/vue' {
  interface Vue {
    $mtd: {
      confirm: MTDConfirm
      message: MTDMessage
      notify: MTDNotification
    }
  }
}
