/* Automatically generated by './build/bin/build-ts.js' */
import { Button } from './button';
import { Row } from './row';
import { Col } from './col';
import { Icon } from './icon';
import { ButtonGroup } from './button-group';
import { Input } from './input';
import { Confirm as WTConfirm } from './confirm';
import {
  Message as WTMessage,
  MessageOptions
} from './message';
import {
  Notification as WTNotification,
  NotificationOptions
} from './notification';
import { FormRule, FormRules } from './form';
import CollapseTransition from './collapse-transition';

export const Message: WTMessage;
export const Notification: WTNotification;
export const Confirm: WTConfirm;

export {
  Button,
  Row,
  Col,
  Icon,
  ButtonGroup,
  Input,
  FormRule,
  FormRules,
  NotificationOptions,
  MessageOptions,
  CollapseTransition,
};

export declare function install(vue: any): void;

declare module 'vue/types/vue' {
  interface Vue {
    $wt: {
      confirm: WTConfirm
      message: WTMessage
      notify: WTNotification
    }
  }
}
