/* Automatically generated by './build/bin/build-ts.js' */
import { Button } from './button';
import { Row } from './row';
import { Col } from './col';
import { Confirm as WDConfirm } from './confirm';
import {
  Message as WDMessage,
  MessageOptions
} from './message';
import {
  Notification as WDNotification,
  NotificationOptions
} from './notification';
import { FormRule, FormRules } from './form';
import CollapseTransition from './collapse-transition';

export const Message: WDMessage;
export const Notification: WDNotification;
export const Confirm: WDConfirm;

export {
  Button,
  Row,
  Col,
  FormRule,
  FormRules,
  NotificationOptions,
  MessageOptions,
  CollapseTransition,
};

export declare function install(vue: any): void;

declare module 'vue/types/vue' {
  interface Vue {
    $wd: {
      confirm: WDConfirm
      message: WDMessage
      notify: WDNotification
    }
  }
}
