/* Automatically generated by './build/bin/build-entry.js' TODO 打开下面注释 */
import Button from 'components/button';
import Row from 'components/row';
import Col from 'components/col';
import Icon from 'components/icon';
import ButtonGroup from 'components/button-group';
import CollapseTransition from './transitions/collapse-transition';

const components = [
  Button,
  Row,
  Col,
  Icon,
  ButtonGroup,
  CollapseTransition,
];

export function install (Vue) {
  components.map(function (component) {
    Vue.component(component.name, component);
  });

  const $wd = {
    // confirm: Confirm,
    // notify: Notification,
    // message: Message,
  };

  if (Vue.prototype) Vue.prototype.$wd = $wd;
  if (Vue.config.globalProperties) Vue.config.globalProperties.$wd = $wd;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export {
  Button,
  Row,
  Col,
  Icon,
  ButtonGroup,
  CollapseTransition,
};

export default {
  version: '0.0.2-alpha.25',
  install,
};
